### ISSUE TITLE
How to enable docker build cache on gcr plugin.

### ISSUE THREAD

**Issue by sabrehagen** [drone/drone-plugin-index#100]
The [gcr plugin](https://github.com/drone/drone-plugin-index/blob/master/content/drone-plugins/drone-gcr/index.md)  builds the container from scratch every time. How can I turn on build caching?

**Comment by tboerger** [comment]
It's up to the user to use one of the available cache plugins, the docker, ecr and gcr plugins are all the same related to that.

**Comment by tboerger** [comment]
Closing this since this is not really an issue with the plugin index.
