### ISSUE TITLE
theme has been ignored

### ISSUE THREAD

**Issue by lizheming** [drone/drone-plugin-index#101]
https://github.com/drone/drone-plugin-index/blob/master/.gitignore#L2

#23 and #78 should update theme files. But hugo theme "drone-hugo-theme" not include in repo, so we can't update site by pull request.

**Comment by tboerger** [comment]
Of course it's ignored, because the theme is managed within a dedicated repository. You can find it at https://github.com/drone/drone-hugo-theme.

**Comment by lizheming** [comment]
OK, thank you very much. I have not check repo list  carefully.
