### ISSUE TITLE
Automate generation of Drone plugin index

### ISSUE THREAD

**Issue by donny-dont** [drone/drone-plugin-index#109]
It would be nice if there were some way for a plugin to automate its documentation on the drone-plugin-index.

Perhaps a docs directory that would then get downloaded during the generation process to make the process easier?

**Comment by donny-dont** [comment]
@tboerger @bradrydzewski I have a few repos that aren't on the drone-plugin-index so I'm interested in figuring out a way to automate this all.

One thing that might be cool is creating a github app that people with a drone plugin can install on their directory. That way it could get updates look for changes to the docs directory, or whatever, and if so trigger a build on the plugin index.

Honestly it would also be nice to have thing integrated into the Drone UI so you could look for a plugin specifically. I remember there being a white list of things so perhaps there's a way to have the server look at different plugin registries and then present those in a way to the user so they know what's available.

**Comment by tboerger** [comment]
But we are moving at least for drone-plugins to the centralized plugin index documentation. So what needs to be automated there?

**Comment by donny-dont** [comment]
@tboerger maybe I've just been out of the loop on what's happening with the centralized plugin index documentation.

What I'm wondering is if there's some way to automate the workflow for plugin authors so that any documentation changes are propagated to the centralized registry.

One thing I've been seeing lately for workflow is https://probot.github.io/ which lets you easily write GitHub apps. Its probably something that the drone go-scm/go-login stuff could probably do with a nice little layering.

So workflow-wise what if you had a drone-plugins-bot.

1. User adds drone-plugins-bot to its authorized applications.
2. The drone-plugin-bot scans repos for drone plugins, maybe there's some standard folder structure or something that it could look for.
3. It opens a PR on the plugins index adding each repo.
4. The plugin is approved and the commit is merged.
5. The drone-plugin-bot gets events from the repos that have been enabled and if something within the folder structure that applies to a plugin is updated then a build is triggered on the plugins registry which would update the directories and create a new build. Or maybe it just creates a PR with the updated documentation to verify before letting it be public.

This way all the documentation is controlled within the repo with the plugin.

Then potentially there could be a JSON endpoint that just has all the plugins in it. Then the drone server could hit this and potentially update the site to contain the updated documentation. You could go further and run the drone-plugins index on prem and have your own plugins in there.

Idea is to beam what plugins are there for the users to add and have that be there within the drone site you have.

**Comment by tphoney** [comment]
The deployment of the  new website has happened, closing the ticket
