### ISSUE TITLE
How to custom the registry_mirrors?

### ISSUE THREAD

**Issue by JerryChaox** [drone/drone-plugin-index#159]
```
sudo tee /etc/docker/daemon.json <<-'EOF'
{
  "registry-mirrors": ["https://8cd6965c.mirror.aliyuncs.com"]
}
```

**Comment by tboerger** [comment]
Sorry, but this is not really related to the plugin index. Maybe you should use our forum at discourse.drone.io or you should raise an issue at the right plugin repository.

**Comment by JerryChaox** [comment]
Sorry, i make a mistake.
