### ISSUE TITLE
[s3-sync] Bucket name appears twice and minimum s3 permissions are not documented

### ISSUE THREAD

**Issue by rverma-nikiai** [drone/drone-plugin-index#165]
For plugin s3-sync, in all the examples bucket appears twice which is not valid.
Also I couldn't make plugin to work with below policy
```
"s3:PutObjectAcl",
 "s3:PutObject",
 "s3:GetObject",
 "s3:DeleteObject",
  "s3:AbortMultipartUpload"
```
My bucket is versioned and not encrypted. Would be helpful to highlight minimum iam policy along with plugin.

**Comment by tboerger** [comment]
> For plugin s3-sync, in all the examples bucket appears twice which is not valid.

It's not nice and a minor bug, but it's not invalid... the latter value just overwrites the other one.

> My bucket is versioned and not encrypted. Would be helpful to highlight minimum iam policy along with plugin.

I'm personally only using Minio as a target, so there somebody else got to help. Until somebody provides a sample for that you can experiment with the permissions and invoke the command manually as explained [here](https://github.com/drone-plugins/drone-s3-sync#usage)
