### ISSUE TITLE
Updating docs for 1.0

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-plugin-index#167]
Starting tomorrow I'm going to be updating the documentation for 1.0.  I will snapshot the 0.8 documentation so that it remains available. There will be a window of a few hours where the plugin docs are published, with updates, without a link to the 0.8 plugin docs. I pre-apologize for this, and will try to get it resolved asap.

**Comment by lizheming** [comment]
thank you for your working, i have create pr #169 for my plugin drone-wechat to  relieve your stress.

**Comment by tonglil** [comment]
Hey @bradrydzewski, is the 0.8 doc snapshot up?
