### ISSUE TITLE
Uploads impossible on some GitHub Enterprise systems

### ISSUE THREAD

**Issue by agethecoolguy** [drone/drone-plugin-index#209]
Due to the way this plugin constructs the upload URL, uploads are impossible on certain GitHub Enterprise systems.

For example, by default the GHE uses `https://media.github.mycompany.com/releases/xxxx/files` as the upload URL. However, if a user specifies `https://media.github.mycompany.com` in the plugin's `upload_url` parameter, the plugin attempts to use `https://media.github.mycompany.com/repos/zzzz/yyyy/releases/xxxx/assets`, resulting in an error.

This can be easily remedied by simply using the value of `upload_url` or `assets_url` provided in the response for `GET/POST/PATCH /repos/:owner/:repo/releases/:release_id` [(see documentation here)](https://developer.github.com/v3/repos/releases/#upload-a-release-asset).

As it stands, the plugin's `upload_url` parameter is unnecessary and confusing, as the correct value is always returned in the REST response. Implementing this would also allow you to remove the parameter entirely.

**Comment by tboerger** [comment]
Which plugin are you talking about? You are posting this on the plugin index, this repo is simply listing and documenting the available plugins.

Please open an issue in the right repository.
