### ISSUE TITLE
plugins/docker mirror more

### ISSUE THREAD

**Issue by 120011676** [drone/drone-plugin-index#223]
![image](https://user-images.githubusercontent.com/1992933/61358981-10bb5880-a8ae-11e9-9044-e0e492a14df2.png)
![image](https://user-images.githubusercontent.com/1992933/61359035-2cbefa00-a8ae-11e9-9b68-fb9fde5b6616.png)

**Comment by tboerger** [comment]
Same here, how should that apply to the plugin index?
