### ISSUE TITLE
plugins/docker mirror timeout

### ISSUE THREAD

**Issue by 120011676** [drone/drone-plugin-index#224]
![image](https://user-images.githubusercontent.com/1992933/61359336-b2db4080-a8ae-11e9-9ccd-f2c55d0667ba.png)

![image](https://user-images.githubusercontent.com/1992933/61359416-d7371d00-a8ae-11e9-9813-3fce5dbb0f9b.png)
![image](https://user-images.githubusercontent.com/1992933/61359521-08afe880-a8af-11e9-8d63-aebb5c25a92d.png)

**Comment by tboerger** [comment]
And what should we do with this issue on the plugin index?
