### ISSUE TITLE
[mike1pol/drone-rocket] docs is outdated

### ISSUE THREAD

**Issue by NateScarlet** [drone/drone-plugin-index#228]
The [Template Reference](http://plugins.drone.io/mike1pol/drone-rocket/) section is not match to <https://github.com/mike1pol/drone-rocket/blob/7cc780ad8df0fbf2429e5a7e4a8d64aa41a1a141/plugin.go#L14-L74>

@mike1pol

**Comment by tboerger** [comment]
Create a PR if you find outdated information.
