### ISSUE TITLE
CSS isn't available in development

### ISSUE THREAD

**Issue by ErinCall** [drone/drone-plugin-index#254]
When running `hugo server`, the root page (but not the pages for individual plugins) doesn't have any styling. I spent a little time poking around in `layouts.index.html`, but I wasn't able to find a fix.

I was able to work around it by changing [the reference to `style.min.css`](https://github.com/drone/drone-plugin-index/blob/master/layouts/index.html#L16) to point to plugins.drone.io rather than `.Site.BaseURL`.

**Comment by amirbagh75** [comment]
same problem

**Comment by tboerger** [comment]
@bradrydzewski where does http://plugins.drone.io/dist/style.min.css come from? It's not part of the theme...

**Comment by tphoney** [comment]
The deployment of the  new website has happened, closing the ticket
