### ISSUE TITLE
Add new index plugin

### ISSUE THREAD

**Issue by wesleimp** [drone/drone-plugin-index#267]
The **drone-circleci** plugin allows to trigger circle-ci builds

- [Repo](https://github.com/wesleimp/drone-circleci)
- [Docs](https://github.com/wesleimp/drone-circleci/blob/master/DOCS.md)

**Comment by bradrydzewski** [comment]
please fork and submit a pull request that adds your plugin to the docs.  thanks!!

**Comment by tboerger** [comment]
Closing this as there is already a PR and creating an issue before is not required.
