### ISSUE TITLE
[request] Plugin to publish Cloud Native Buildpacks

### ISSUE THREAD

**Issue by ShadowJonathan** [drone/drone-plugin-index#277]
Inspired by https://dokku.github.io/technology/comparing-buildpack-v3-to-herokuish

Currently Buildpacks are an interesting and easy way to generate build artifacts in the form of container images, cloud-native buildpacks are a second step for this, building on the proprietary format that heroku established, but standardising it.

Currently CNB isn't entirely stable or released (afaik), but such a plugin that builds images as part of a pipeline would be a very useful part of the drone.io plugin ecosystem.

*PS: I don't know if this is the right spot to issue plugin requests, please correct me if I'm wrong*

**Comment by tboerger** [comment]
This is indeed the wrong place to ask for a plugin. You could give it a try to post on discourse.drone.io, but your best choice would be to get your hands dirty and build a plugin like that.

You can use any language for that, you are not forced to use Go.

**Comment by ShadowJonathan** [comment]
Thanks for clarifying, I mostly wanted to use an issue like this as a rallying point, I'm currently full with work and thus I can't invest the time yet to start working on this.

I'll come back to this on discourse, again, thanks for the quick response.
