### ISSUE TITLE
Ask Permission Questions

### ISSUE THREAD

**Issue by dxl568736988** [drone/drone-plugin-index#364]
Unable to locate credentials. You can configure credentials by running "aws configure".
When I set aws_access_key_id and aws_secret_access_key, I will be prompted that I do not have permission, but I do have permission, what is wrong? How does iam Role work without specifying a key?

**Comment by bradrydzewski** [comment]
:wave: hey there, for end-user support please post questions to our [mailing list](https://community.harness.io/).
