### ISSUE TITLE
Does appleboy/drone-scp support IPv6? I encountered an error while using IPv6

### ISSUE THREAD

**Issue by fjiabinc** [drone/drone-plugin-index#406]
latest: Pulling from appleboy/drone-scp
Digest: sha256:eb6845ad3b2218e45fc21fede10a8aba1a17d2c0657506fcff572ccc505f1cdb
Status: Image is up to date for appleboy/drone-scp:latest
drone-scp version: v1.6.11
tar all files into /tmp/XJPePYLibx.tar.gz
remote server os type is unix
scp file to server.
drone-scp error:  error copy file to dest: test.fjiabinc.cn, error message: dial tcp [240e:3a1:58f0:7af1::4bc]:22: connect: cannot assign requested address

2023/07/17 09:03:34 error copy file to dest: test.fjiabinc.cn, error message: dial tcp [240e:3a1:58f0:7af1::4bc]:22: connect: cannot assign requested address

**Comment by d1wilko** [comment]
@fjiabinc we do not maintain this plugin - it might be better to ask in the repo - https://github.com/appleboy/drone-scp
