### ISSUE TITLE
Guidlines for publishing?

### ISSUE THREAD

**Issue by ViViDboarder** [drone/drone-plugin-index#60]
Are there any guidelines for how to publish a plugin?

I've written a small plugin that I've been using myself for a while to publish compiled artifacts to a Webdav server (Nextcloud) and thought others could find it useful.

https://github.com/vividboarder/drone-webdav

**Comment by appleboy** [comment]
See the closed PR list https://github.com/drone/drone-plugin-index/pulls?q=is%3Apr+is%3Aclosed

**Comment by ViViDboarder** [comment]
Well, now I feel silly. That's a great idea. Thanks!
